import {
  MessageCirclePlus,
  DollarSign,
  SmileIcon,
  Book,
  Bed,
  Bot,
  Medal,
  MessageSquareHeart,
  Goal,
  TrophyIcon,
  Calendar,
  Dumbbell,
  PenBoxIcon,
} from "lucide-react";

export const sidebarRoutes = [
  {
    label: "dashboard",
    icon: MessageCirclePlus,
    href: "/dashboard",
    color: "text-sky-500",
  },
  {
    label: "Achievements",
    icon: TrophyIcon,
    href: "/achievements",
    color: "text-sky-500",
  },
  {
    label: "Bio Hacking",
    icon: SmileIcon,
    href: "/bio-hacking",
    color: "text-orange-500",
  },
  {
    label: "AI Trends Analysis",
    icon: Book,
    href: "/ai-trends-analysis",
    color: "text-orange-500",
  },
  {
    label: "Daily Goals",
    icon: Goal,
    href: "daily-goals",
    color: "text-orange-500",
  },
  {
    label: "Journals",
    icon: Bed,
    href: "/journals",
    color: "text-orange-500",
  },
  {
    label: "Progress Achievements",
    icon: Medal,
    href: "/progress-achievements",
    color: "text-orange-500",
  },
  {
    label: "Calander",
    icon: Calendar,
    href: "/calander",
    color: "text-orange-500",
  },
  // {
  //   label: "Zen Zone Meditation Log",
  //   icon: Calendar,
  //   href: "/zen-zone",
  //   color: "text-orange-500",
  // },
  {
    label: "Quiz",
    icon: PenBoxIcon,
    href: "/quiz",
    color: "text-orange-500",
  },
  {
    label: "Inspiration Feeds",
    icon: MessageSquareHeart,
    href: "/inspiration-feeds",
    color: "text-orange-500",
  },
  {
    label: "Exercise Tracker",
    icon: Dumbbell,
    href: "/exercise-tracker",
    color: "text-orange-500",
  },
  {
    label: "Improvement Advisor",
    icon: Bot,
    href: "/improvement-advisor",
    color: "text-pink-400",
  },
  {
    label: "Manage Subscriptions",
    icon: DollarSign,
    href: "/manage_subscriptions",
    color: "text-pink-400",
  },
];
