import {
  DollarSign,
  SmileIcon,
  Medal,
  MessageSquareHeart,
  Goal,
  TrophyIcon,
  Calendar,
  Dumbbell,
  PenBoxIcon,
  TrendingUp,
  MenuSquare,
  BotMessageSquareIcon,
  BookCopyIcon,
  Brain,
} from "lucide-react";

export const sidebarRoutes = [
  {
    label: "Dashboard",
    icon: MenuSquare,
    href: "/dashboard",
    color: "text-sky-500",
    bgColor: "text-sky-500",
  },
  {
    label: "Personal Growth Dashboard",
    icon: TrendingUp,
    href: "/personal-growth-dashboard",
    color: "text-sky-500",
  },
  {
    label: "Achievements",
    icon: TrophyIcon,
    href: "/achievements",
    color: "text-sky-500",
  },
  {
    label: "Bio Hacking",
    icon: SmileIcon,
    href: "/bio-hacking",
    color: "text-orange-500",
  },
  {
    label: "AI Trends Analysis",
    icon: Brain,
    href: "/ai-trends-analysis",
    color: "text-orange-500",
  },
  {
    label: "Daily Goals",
    icon: Goal,
    href: "daily-goals",
    color: "text-orange-500",
  },
  {
    label: "Journals",
    icon: BookCopyIcon,
    href: "/journals",
    color: "text-orange-500",
  },
  {
    label: "Progress Achievements",
    icon: Medal,
    href: "/progress-achievements",
    color: "text-orange-500",
  },
  {
    label: "Calendar",
    icon: Calendar,
    href: "/calendar",
    color: "text-orange-500",
  },
  // {
  //   label: "Zen Zone Meditation Log",
  //   icon: Calendar,
  //   href: "/zen-zone",
  //   color: "text-orange-500",
  // },
  {
    label: "Quiz",
    icon: PenBoxIcon,
    href: "/quiz",
    color: "text-orange-500",
  },
  {
    label: "Inspiration Feeds",
    icon: MessageSquareHeart,
    href: "/inspiration-feeds",
    color: "text-orange-500",
  },
  {
    label: "Exercise Tracker",
    icon: Dumbbell,
    href: "/exercise-tracker",
    color: "text-orange-500",
  },
  {
    label: "Improvement Advisor",
    icon: BotMessageSquareIcon,
    href: "/improvement-advisor",
    color: "text-pink-400",
  },
  {
    label: "Manage Subscriptions",
    icon: DollarSign,
    href: "/manage_subscriptions",
    color: "text-pink-400",
  },
];
